export const AUDIT_ACTIONS = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT: "LOGOUT",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  PASSWORD_RESET: "PASSWORD_RESET",
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_DELETED: "USER_DELETED",
  ROLE_CHANGED: "ROLE_CHANGED",
  TEAM_CREATED: "TEAM_CREATED",
  TEAM_UPDATED: "TEAM_UPDATED",
  TEAM_DELETED: "TEAM_DELETED",
  PLAYER_CREATED: "PLAYER_CREATED",
  PLAYER_UPDATED: "PLAYER_UPDATED",
  PLAYER_DELETED: "PLAYER_DELETED",
  PLAYER_TRANSFERRED: "PLAYER_TRANSFERRED",
  PLAYER_ANONYMIZED: "PLAYER_ANONYMIZED",
  FIXTURES_GENERATED: "FIXTURES_GENERATED",
  FIXTURE_CREATED: "FIXTURE_CREATED",
  FIXTURE_UPDATED: "FIXTURE_UPDATED",
  FIXTURE_DELETED: "FIXTURE_DELETED",
  MATCH_STARTED: "MATCH_STARTED",
  MATCH_ENDED: "MATCH_ENDED",
  MATCH_SCORE_UPDATED: "MATCH_SCORE_UPDATED",
  MATCH_EVENT_ADDED: "MATCH_EVENT_ADDED",
  ORGANIZATION_UPDATED: "ORGANIZATION_UPDATED",
  DATA_EXPORTED: "DATA_EXPORTED",
  MATCH_REPORT_SUBMITTED: "MATCH_REPORT_SUBMITTED",
  MATCH_REPORT_ANALYZED: "MATCH_REPORT_ANALYZED",
  MATCH_REPORT_ANALYSIS_FAILED: "MATCH_REPORT_ANALYSIS_FAILED",
  MATCH_EVENT_CORRECTED: "MATCH_EVENT_CORRECTED",
  MATCH_EVENTS_CONFIRMED: "MATCH_EVENTS_CONFIRMED",
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

export const AUDIT_CATEGORIES = {
  AUTHENTICATION: "AUTHENTICATION",
  AUTHORIZATION: "AUTHORIZATION",
  USER_MANAGEMENT: "USER_MANAGEMENT",
  FOOTBALL_DATA: "FOOTBALL_DATA",
  SYSTEM: "SYSTEM",
} as const;

export type AuditCategory = (typeof AUDIT_CATEGORIES)[keyof typeof AUDIT_CATEGORIES];

export const AUDIT_SEVERITIES = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  CRITICAL: "CRITICAL",
} as const;

export type AuditSeverity = (typeof AUDIT_SEVERITIES)[keyof typeof AUDIT_SEVERITIES];

export const ACTION_CATEGORY: Record<AuditAction, AuditCategory> = {
  LOGIN_SUCCESS: AUDIT_CATEGORIES.AUTHENTICATION,
  LOGIN_FAILED: AUDIT_CATEGORIES.AUTHENTICATION,
  LOGOUT: AUDIT_CATEGORIES.AUTHENTICATION,
  PASSWORD_CHANGED: AUDIT_CATEGORIES.AUTHENTICATION,
  PASSWORD_RESET: AUDIT_CATEGORIES.AUTHENTICATION,
  USER_CREATED: AUDIT_CATEGORIES.USER_MANAGEMENT,
  USER_UPDATED: AUDIT_CATEGORIES.USER_MANAGEMENT,
  USER_DELETED: AUDIT_CATEGORIES.USER_MANAGEMENT,
  ROLE_CHANGED: AUDIT_CATEGORIES.AUTHORIZATION,
  TEAM_CREATED: AUDIT_CATEGORIES.USER_MANAGEMENT,
  TEAM_UPDATED: AUDIT_CATEGORIES.USER_MANAGEMENT,
  TEAM_DELETED: AUDIT_CATEGORIES.USER_MANAGEMENT,
  PLAYER_CREATED: AUDIT_CATEGORIES.FOOTBALL_DATA,
  PLAYER_UPDATED: AUDIT_CATEGORIES.FOOTBALL_DATA,
  PLAYER_DELETED: AUDIT_CATEGORIES.FOOTBALL_DATA,
  PLAYER_TRANSFERRED: AUDIT_CATEGORIES.FOOTBALL_DATA,
  PLAYER_ANONYMIZED: AUDIT_CATEGORIES.USER_MANAGEMENT,
  FIXTURES_GENERATED: AUDIT_CATEGORIES.FOOTBALL_DATA,
  FIXTURE_CREATED: AUDIT_CATEGORIES.FOOTBALL_DATA,
  FIXTURE_UPDATED: AUDIT_CATEGORIES.FOOTBALL_DATA,
  FIXTURE_DELETED: AUDIT_CATEGORIES.FOOTBALL_DATA,
  MATCH_STARTED: AUDIT_CATEGORIES.FOOTBALL_DATA,
  MATCH_ENDED: AUDIT_CATEGORIES.FOOTBALL_DATA,
  MATCH_SCORE_UPDATED: AUDIT_CATEGORIES.FOOTBALL_DATA,
  MATCH_EVENT_ADDED: AUDIT_CATEGORIES.FOOTBALL_DATA,
  ORGANIZATION_UPDATED: AUDIT_CATEGORIES.SYSTEM,
  DATA_EXPORTED: AUDIT_CATEGORIES.SYSTEM,
  MATCH_REPORT_SUBMITTED: AUDIT_CATEGORIES.SYSTEM,
  MATCH_REPORT_ANALYZED: AUDIT_CATEGORIES.SYSTEM,
  MATCH_REPORT_ANALYSIS_FAILED: AUDIT_CATEGORIES.SYSTEM,
  MATCH_EVENT_CORRECTED: AUDIT_CATEGORIES.FOOTBALL_DATA,
  MATCH_EVENTS_CONFIRMED: AUDIT_CATEGORIES.FOOTBALL_DATA,
};

export const ACTION_SEVERITY: Record<AuditAction, AuditSeverity> = {
  LOGIN_SUCCESS: AUDIT_SEVERITIES.LOW,
  LOGIN_FAILED: AUDIT_SEVERITIES.MEDIUM,
  LOGOUT: AUDIT_SEVERITIES.LOW,
  PASSWORD_CHANGED: AUDIT_SEVERITIES.HIGH,
  PASSWORD_RESET: AUDIT_SEVERITIES.HIGH,
  USER_CREATED: AUDIT_SEVERITIES.MEDIUM,
  USER_UPDATED: AUDIT_SEVERITIES.MEDIUM,
  USER_DELETED: AUDIT_SEVERITIES.HIGH,
  ROLE_CHANGED: AUDIT_SEVERITIES.HIGH,
  TEAM_CREATED: AUDIT_SEVERITIES.LOW,
  TEAM_UPDATED: AUDIT_SEVERITIES.LOW,
  TEAM_DELETED: AUDIT_SEVERITIES.HIGH,
  PLAYER_CREATED: AUDIT_SEVERITIES.LOW,
  PLAYER_UPDATED: AUDIT_SEVERITIES.LOW,
  PLAYER_DELETED: AUDIT_SEVERITIES.MEDIUM,
  PLAYER_TRANSFERRED: AUDIT_SEVERITIES.MEDIUM,
  PLAYER_ANONYMIZED: AUDIT_SEVERITIES.HIGH,
  FIXTURES_GENERATED: AUDIT_SEVERITIES.MEDIUM,
  FIXTURE_CREATED: AUDIT_SEVERITIES.LOW,
  FIXTURE_UPDATED: AUDIT_SEVERITIES.LOW,
  FIXTURE_DELETED: AUDIT_SEVERITIES.HIGH,
  MATCH_STARTED: AUDIT_SEVERITIES.MEDIUM,
  MATCH_ENDED: AUDIT_SEVERITIES.MEDIUM,
  MATCH_SCORE_UPDATED: AUDIT_SEVERITIES.MEDIUM,
  MATCH_EVENT_ADDED: AUDIT_SEVERITIES.LOW,
  ORGANIZATION_UPDATED: AUDIT_SEVERITIES.HIGH,
  DATA_EXPORTED: AUDIT_SEVERITIES.MEDIUM,
  MATCH_REPORT_SUBMITTED: AUDIT_SEVERITIES.LOW,
  MATCH_REPORT_ANALYZED: AUDIT_SEVERITIES.LOW,
  MATCH_REPORT_ANALYSIS_FAILED: AUDIT_SEVERITIES.MEDIUM,
  MATCH_EVENT_CORRECTED: AUDIT_SEVERITIES.MEDIUM,
  MATCH_EVENTS_CONFIRMED: AUDIT_SEVERITIES.HIGH,
};

export function categoryFor(action: string): AuditCategory {
  return ACTION_CATEGORY[action as AuditAction] ?? AUDIT_CATEGORIES.SYSTEM;
}

export function severityFor(action: string): AuditSeverity {
  return ACTION_SEVERITY[action as AuditAction] ?? AUDIT_SEVERITIES.LOW;
}

export const ACTION_LABELS: Record<string, string> = {
  LOGIN_SUCCESS: "Login Succeeded",
  LOGIN_FAILED: "Login Failed",
  LOGOUT: "Logout",
  PASSWORD_CHANGED: "Password Changed",
  PASSWORD_RESET: "Password Reset",
  USER_CREATED: "User Created",
  USER_UPDATED: "User Updated",
  USER_DELETED: "User Deleted",
  ROLE_CHANGED: "Role Changed",
  TEAM_CREATED: "Team Created",
  TEAM_UPDATED: "Team Updated",
  TEAM_DELETED: "Team Deleted",
  PLAYER_CREATED: "Player Created",
  PLAYER_UPDATED: "Player Updated",
  PLAYER_DELETED: "Player Deleted",
  PLAYER_TRANSFERRED: "Player Transferred",
  PLAYER_ANONYMIZED: "Player Anonymized",
  FIXTURES_GENERATED: "Fixtures Generated",
  FIXTURE_CREATED: "Fixture Created",
  FIXTURE_UPDATED: "Fixture Updated",
  FIXTURE_DELETED: "Fixture Deleted",
  MATCH_STARTED: "Match Started",
  MATCH_ENDED: "Match Ended",
  MATCH_SCORE_UPDATED: "Score Updated",
  MATCH_EVENT_ADDED: "Match Event Added",
  ORGANIZATION_UPDATED: "Organization Updated",
  DATA_EXPORTED: "Data Exported",
  MATCH_REPORT_SUBMITTED: "Match Report Submitted",
  MATCH_REPORT_ANALYZED: "Match Report Analyzed",
  MATCH_REPORT_ANALYSIS_FAILED: "Match Report Analysis Failed",
  MATCH_EVENT_CORRECTED: "Match Event Corrected",
  MATCH_EVENTS_CONFIRMED: "Match Events Confirmed",
};

export function actionLabel(action: string): string {
  return (
    ACTION_LABELS[action] ??
    action
      .replace(/_/g, " ")
      .toLowerCase()
      .replace(/^\w/, (c) => c.toUpperCase())
  );
}

/** Map legacy event_type strings (snake_case) to structured actions. */
export function normalizeAction(eventType: string): string {
  if (!eventType) return eventType;
  const lower = eventType.toUpperCase();
  if (lower in ACTION_LABELS) return lower;
  if (lower.includes("LOGIN")) return "LOGIN_SUCCESS";
  if (lower.includes("LOGOUT")) return "LOGOUT";
  if (lower.includes("TEAM_CREATE")) return "TEAM_CREATED";
  if (lower.includes("FIXTURE") && lower.includes("GENERAT")) return "FIXTURES_GENERATED";
  if (lower.includes("SCORE") || (lower.includes("FIXTURE") && lower.includes("UPDATE")))
    return "MATCH_SCORE_UPDATED";
  if (lower.includes("PLAYER_CREATE")) return "PLAYER_CREATED";
  if (lower.includes("PLAYER") && lower.includes("UPDATE")) return "PLAYER_UPDATED";
  return eventType;
}
