-- Store anonymous web-push endpoints server-side. The table is only read and
-- written by the service-role API; browser clients never receive its keys.
CREATE TABLE IF NOT EXISTS public_push_subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  endpoint TEXT NOT NULL UNIQUE,
  p256dh TEXT NOT NULL,
  auth TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public_push_subscriptions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public_push_subscriptions FROM anon, authenticated;
GRANT ALL ON public_push_subscriptions TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public_push_subscriptions_id_seq TO service_role;

ALTER TABLE fixtures
  ADD COLUMN IF NOT EXISTS halftime_notified_at TIMESTAMPTZ;

-- Keep existing public_matches fields in order, then append the live-page data.
CREATE OR REPLACE VIEW public_matches AS
SELECT
  f.id AS match_id,
  f.round,
  COALESCE(ht.name, 'Unknown team') AS home_team_name,
  COALESCE(at.name, 'Unknown team') AS away_team_name,
  f.home_score,
  f.away_score,
  f.status,
  f.date,
  f.time::TEXT,
  f.venue,
  ht.logo_url AS home_team_logo,
  at.logo_url AS away_team_logo,
  f.live_started_at,
  f.competition_id,
  COALESCE(
    CASE WHEN c.settings->>'halftimeMinutes' ~ '^[0-9]{1,3}$'
      THEN (c.settings->>'halftimeMinutes')::INTEGER END,
    15
  ) AS halftime_minutes,
  COALESCE(
    CASE WHEN c.settings->>'stoppageMinutes' ~ '^[0-9]{1,3}$'
      THEN (c.settings->>'stoppageMinutes')::INTEGER END,
    3
  ) AS stoppage_minutes
FROM fixtures f
LEFT JOIN teams ht ON ht.id = f.home_team_id
LEFT JOIN teams at ON at.id = f.away_team_id
LEFT JOIN competitions c ON c.id = f.competition_id
WHERE f.status IN ('live', 'in-progress', 'completed')
   OR (f.status = 'scheduled' AND f.date IS NOT NULL AND f.time IS NOT NULL);

GRANT SELECT ON public_matches TO anon;

-- Extend the existing narrow public event view with an opted-in player photo
-- while preserving the organization's name-visibility setting.
CREATE OR REPLACE VIEW public_live_events AS
SELECT
  f.id AS match_id,
  f.round,
  f.competition_id,
  f.season_id,
  c.organization_id,
  COALESCE(o.public_player_names_enabled, FALSE) AS public_player_names_enabled,
  f.home_team_id,
  ht.name AS home_team_name,
  ht.logo_url AS home_team_logo,
  f.away_team_id,
  at.name AS away_team_name,
  at.logo_url AS away_team_logo,
  f.home_score,
  f.away_score,
  f.status,
  f.date,
  f.time::TEXT,
  f.venue,
  me.id AS event_id,
  me.event_type,
  me.minute,
  me.team_id,
  CASE WHEN COALESCE(o.public_player_names_enabled, FALSE) THEN p.name ELSE NULL END AS player_name,
  p.id AS player_id,
  CASE WHEN COALESCE(o.public_player_names_enabled, FALSE) THEN p.photo_url ELSE NULL END AS player_photo_url
FROM match_events me
JOIN fixtures f ON f.id = me.match_id
JOIN competitions c ON c.id = f.competition_id
LEFT JOIN teams ht ON ht.id = f.home_team_id
LEFT JOIN teams at ON at.id = f.away_team_id
LEFT JOIN players p ON p.id = me.player_id
LEFT JOIN organizations o ON o.id = c.organization_id
WHERE f.status IN ('live', 'in-progress', 'completed')
   OR (f.status = 'scheduled' AND f.date = CURRENT_DATE);

GRANT SELECT ON public_live_events TO anon;
